

"use strict";

module.exports = {
	USER: 'user_v1_',
	AUTH_TOKEN: 'auth_token_V1_',
	POST_COUNT: 'POST_COUNT_V1',
	TODO_RANGE: 'TODO_RANGE_V1',
	TODO_COUNT: 'TODO_COUNT_V1',
	POST_RANGE_COMMENT: 'POST_RANGE_V1_',
	POST_COUNT_COMMENT: 'POST_COUNT_V1_',
	USER_POST: 'USER_POST_V1',
	USER_TODO: 'USER_TODO_V1',
	POST_RANGE: 'POST_RANGE_V1',
	USER_RANGE: 'USER_RANGE_V1',
	USER_COUNT: 'USER_COUNT_V1',
	TODO_ID: 'TODO_ID_V1_',
	USER_ID: 'USER_ID_V1_',
	USER_TODO_COUNT: 'USER_TODO_COUNT_V1_',
	USER_POST_COUNT: 'USER_POST_COUNT_V1_',
};